# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d7d5f563a30974d7d24a0edd196fe5aa5ba2f473acfdb4763d65521fb12b08f262c85d0fdfd5f233115a43ac487039b25a55ec8ab0b53b1671542972a2a69b6b

test:
  secret_key_base: 531efb4eb9c9d9276fdf6746243f7560a6b436151ac6798efee9a1d0eee0a355e9f992f6ea5b6c26b0516fe5825c3e641b2cf6e8b63045f9293b2edb5101cea4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
